#!/usr/bin/env python3
"""
magnetic_phase_search_M3A_symmetry_first_fast.py

M3A: symmetry-first magnetic exact node-zero candidate generator.

Purpose
-------
This is the lightweight replacement for the heavy M3 continuous optimizer.

Instead of searching a high-dimensional phase torus, this script searches
for proof-shaped candidates:

    graph involution r
    signed permutation R|v> = sigma_v |r(v)>
    source fixed with sigma_s = +1
    target fixed with sigma_l = -1
    magnetic/signed Hamiltonian H satisfying [H, R] = 0

Then exact source-target node-zero follows from the invariant-sector
criterion:

    [H,R] = 0,
    R|s> = +|s>,
    R|ell> = -|ell>
        => <ell|exp(-itH)|s> = 0 for all t.

What this script discovers
--------------------------
It finds graph supports and sign/phase assignments where the exact
node-zero mechanism is generated by a signed magnetic involution.

This is not arbitrary optimization.  It is proof-shaped candidate
generation.

Dependencies
------------
numpy pandas networkx

Quick run
---------
python magnetic_phase_search_M3A_symmetry_first_fast.py \
    --outdir m3a_outputs \
    --suite small

Larger but still light run
--------------------------
python magnetic_phase_search_M3A_symmetry_first_fast.py \
    --outdir m3a_outputs_medium \
    --suite medium \
    --max-graphs 30 \
    --max-automorphisms 1000 \
    --max-candidates-per-graph 200 \
    --random-signs-per-pair 12

Outputs
-------
m3a_candidates.csv
m3a_phase_records.csv
m3a_flux_records.csv
m3a_graph_records.csv
m3a_summary.csv
"""

from __future__ import annotations

import argparse
import itertools
import json
import math
from dataclasses import dataclass, asdict
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Sequence, Tuple

import numpy as np
import pandas as pd
import networkx as nx
from networkx.algorithms import isomorphism as iso


TWOPI = 2.0 * np.pi
Array = np.ndarray


@dataclass
class Thresholds:
    eps_verify: float = 1e-10
    eps_comm: float = 1e-10
    eps_r2: float = 1e-12
    eps_sector: float = 1e-12
    eps_support: float = 1e-12


@dataclass
class GraphRecord:
    graph_id: str
    graph_class: str
    n: int
    m: int
    cycle_rank: int
    connected: bool
    num_involutions_checked: int
    num_candidates: int
    edges_json: str
    notes: str


@dataclass
class CandidateRecord:
    candidate_id: str
    graph_id: str
    graph_class: str
    n: int
    m: int
    cycle_rank: int
    automorphism_index: int
    sign_assignment_index: int
    source: int
    target: int
    status: str
    proof_route: str
    normalized_objective: float
    max_normalized_moment: float
    raw_objective: float
    max_raw_moment: float
    commutator_norm: float
    r2_error: float
    source_plus_error: float
    target_minus_error: float
    support_error: float
    fixed_edge_obstruction: bool
    num_negative_edges: int
    observed_fluxes: str
    involution_mapping_json: str
    vertex_signs_json: str
    notes: str


def canonical_edges(G: nx.Graph) -> List[Tuple[int, int]]:
    return sorted((min(int(u), int(v)), max(int(u), int(v))) for u, v in G.edges())


def cycle_rank(G: nx.Graph) -> int:
    c = nx.number_connected_components(G)
    return int(G.number_of_edges() - G.number_of_nodes() + c)


def connected_gnm_graph(n: int, m: int, seed: int) -> nx.Graph:
    rng = np.random.default_rng(seed)
    for _ in range(1000):
        G = nx.gnm_random_graph(n, m, seed=int(rng.integers(0, 2**32 - 1)))
        if nx.is_connected(G):
            return nx.convert_node_labels_to_integers(G)
    raise RuntimeError(f"Could not sample connected G({n},{m}).")


def add_cycle_chords(n: int, chords: Sequence[Tuple[int, int]]) -> nx.Graph:
    G = nx.cycle_graph(n)
    for u, v in chords:
        if u != v:
            G.add_edge(int(u) % n, int(v) % n)
    return nx.convert_node_labels_to_integers(G)


def reflected_cycle_chords(n: int, base_chords: Sequence[Tuple[int, int]]) -> nx.Graph:
    """
    Build C_n and add chords closed under reflection r(k)=(-k mod n).
    This creates structured supports where signed-reflection candidates
    are likely.
    """
    G = nx.cycle_graph(n)

    def r(x: int) -> int:
        return (-int(x)) % n

    for u, v in base_chords:
        u, v = int(u) % n, int(v) % n
        G.add_edge(u, v)
        G.add_edge(r(u), r(v))
    return nx.convert_node_labels_to_integers(G)


def grid_graph(rows: int, cols: int, diagonals: bool = False) -> nx.Graph:
    G0 = nx.grid_2d_graph(rows, cols)
    mapping = {node: i for i, node in enumerate(sorted(G0.nodes()))}
    G = nx.relabel_nodes(G0, mapping)

    if diagonals:
        for r in range(rows - 1):
            for c in range(cols - 1):
                a = mapping[(r, c)]
                b = mapping[(r + 1, c + 1)]
                if (r + c) % 2 == 0:
                    G.add_edge(a, b)
                else:
                    a2 = mapping[(r + 1, c)]
                    b2 = mapping[(r, c + 1)]
                    G.add_edge(a2, b2)

    return nx.convert_node_labels_to_integers(G)


def graph_suite(name: str, seed: int) -> List[Tuple[str, str, nx.Graph, str]]:
    rng = np.random.default_rng(seed)
    items: List[Tuple[str, str, nx.Graph, str]] = []

    # Known/structured seeds.
    for n in [8, 10, 12, 14, 16, 20]:
        items.append((f"C{n}", "cycle", nx.cycle_graph(n), "Cycle graph."))

    # Symmetry-preserving chorded cycles.
    items.extend([
        ("C12_ref_chords_a", "reflected_chord_cycle", reflected_cycle_chords(12, [(1, 4), (2, 6)]),
         "C12 with reflection-closed chords."),
        ("C14_ref_chords_a", "reflected_chord_cycle", reflected_cycle_chords(14, [(1, 5), (3, 7)]),
         "C14 with reflection-closed chords."),
        ("C16_ref_chords_a", "reflected_chord_cycle", reflected_cycle_chords(16, [(1, 5), (2, 8), (3, 11)]),
         "C16 with reflection-closed chords."),
        ("C16_ref_chords_b", "reflected_chord_cycle", reflected_cycle_chords(16, [(1, 7), (2, 6), (4, 10)]),
         "Alternative C16 reflection-closed chord support."),
    ])

    # Ladders and circular ladders.
    for n in [4, 5, 6, 8, 10]:
        items.append((f"ladder_{n}", "ladder", nx.convert_node_labels_to_integers(nx.ladder_graph(n)),
                      f"2x{n} ladder graph."))
    for n in [4, 5, 6, 8]:
        items.append((f"circular_ladder_{n}", "circular_ladder",
                      nx.convert_node_labels_to_integers(nx.circular_ladder_graph(n)),
                      f"Circular ladder with {2*n} vertices."))

    # Grids.
    for rows, cols in [(3, 3), (3, 4), (4, 4), (3, 5)]:
        items.append((f"grid_{rows}x{cols}", "grid", grid_graph(rows, cols, diagonals=False),
                      "Rectangular grid graph."))
        items.append((f"grid_diag_{rows}x{cols}", "grid_with_diagonals", grid_graph(rows, cols, diagonals=True),
                      "Grid graph with alternating diagonals."))

    # Platonic/cubic-ish families when available.
    try:
        items.append(("cube_Q3", "hypercube", nx.convert_node_labels_to_integers(nx.hypercube_graph(3)),
                      "3-cube graph."))
    except Exception:
        pass
    try:
        items.append(("octahedral", "platonic", nx.convert_node_labels_to_integers(nx.octahedral_graph()),
                      "Octahedral graph."))
    except Exception:
        pass

    if name in {"medium", "large"}:
        # Random graphs are not symmetry-rich, but we include a few to see if
        # any accidental involutions appear.
        for n, extra in [(10, 4), (12, 5), (14, 6), (16, 8)]:
            m = n - 1 + extra
            G = connected_gnm_graph(n, m, seed=int(rng.integers(0, 2**32 - 1)))
            items.append((f"gnm_n{n}_m{m}", "connected_gnm", G,
                          "Connected random G(n,m); likely few automorphisms."))

        for n, d in [(10, 3), (12, 3), (14, 3), (16, 3)]:
            try:
                G = nx.random_regular_graph(d, n, seed=int(rng.integers(0, 2**32 - 1)))
                if nx.is_connected(G):
                    items.append((f"random_regular_n{n}_d{d}", "random_regular",
                                  nx.convert_node_labels_to_integers(G),
                                  "Random regular graph; may have accidental automorphisms."))
            except Exception:
                pass

    if name == "large":
        for n in [24, 28, 32]:
            items.append((f"C{n}", "cycle", nx.cycle_graph(n), "Larger cycle graph."))
        for n in [12, 14, 16]:
            items.append((f"circular_ladder_{n}", "circular_ladder",
                          nx.convert_node_labels_to_integers(nx.circular_ladder_graph(n)),
                          f"Larger circular ladder with {2*n} vertices."))

    # Deduplicate IDs.
    seen = set()
    out = []
    for gid, cls, G, notes in items:
        if gid in seen:
            continue
        seen.add(gid)
        out.append((gid, cls, nx.convert_node_labels_to_integers(G), notes))
    return out


def automorphism_involutions(G: nx.Graph, max_automorphisms: int) -> List[Dict[int, int]]:
    """
    Enumerate graph automorphisms that are involutions: r(r(v))=v.

    Uses GraphMatcher, capped by max_automorphisms to avoid large
    automorphism groups blowing up.
    """
    matcher = iso.GraphMatcher(G, G)
    out: List[Dict[int, int]] = []
    seen = set()
    checked = 0

    for mapping in matcher.isomorphisms_iter():
        checked += 1
        if checked > max_automorphisms:
            break

        r = {int(k): int(v) for k, v in mapping.items()}

        # Skip identity; it cannot put a fixed target in a negative
        # permutation sector without creating a pure diagonal sign symmetry.
        if all(r[v] == v for v in r):
            continue

        ok = True
        for v in r:
            if r[r[v]] != v:
                ok = False
                break
        if not ok:
            continue

        key = tuple(r[v] for v in sorted(r))
        if key in seen:
            continue
        seen.add(key)
        out.append(r)

    return out


def vertex_orbits_under_involution(G: nx.Graph, r: Dict[int, int]) -> List[Tuple[int, ...]]:
    seen = set()
    orbits: List[Tuple[int, ...]] = []
    for v in sorted(int(x) for x in G.nodes()):
        if v in seen:
            continue
        rv = r[v]
        if rv == v:
            orb = (v,)
        else:
            orb = tuple(sorted((v, rv)))
        for x in orb:
            seen.add(x)
        orbits.append(orb)
    return orbits


def fixed_vertices(r: Dict[int, int]) -> List[int]:
    return sorted(v for v in r if r[v] == v)


def signed_permutation_matrix(G: nx.Graph, r: Dict[int, int], sigma: Dict[int, int]) -> Array:
    n = G.number_of_nodes()
    R = np.zeros((n, n), dtype=float)
    for v in sorted(G.nodes()):
        R[r[int(v)], int(v)] = float(sigma[int(v)])
    return R


def build_signed_magnetic_hamiltonian(
    G: nx.Graph,
    r: Dict[int, int],
    sigma: Dict[int, int],
) -> Tuple[Optional[Array], Optional[Array], bool, int]:
    """
    Build a real signed magnetic adjacency H with phases 0 or pi.

    Condition for signed involution symmetry:
        H_{r(u),r(v)} = sigma_u sigma_v H_{u,v}.

    For each edge orbit under r, choose representative sign +1.  The
    partner edge receives sign sigma_u sigma_v.  If an edge is fixed as
    an unordered edge and sigma_u sigma_v = -1, unit support is impossible;
    that is a fixed-edge obstruction.
    """
    n = G.number_of_nodes()
    edges = canonical_edges(G)
    edge_set = set(edges)
    assigned: Dict[Tuple[int, int], int] = {}

    fixed_edge_obstruction = False

    for e in edges:
        if e in assigned:
            continue

        u, v = e
        e_img = tuple(sorted((r[u], r[v])))
        if e_img not in edge_set:
            # Should not happen for graph automorphism.
            fixed_edge_obstruction = True
            continue

        factor = int(sigma[u] * sigma[v])

        if e_img == e:
            if factor == -1:
                fixed_edge_obstruction = True
                break
            assigned[e] = 1
        else:
            assigned[e] = 1
            assigned[e_img] = factor

    if fixed_edge_obstruction:
        return None, None, True, 0

    H = np.zeros((n, n), dtype=complex)
    raw_phases = np.zeros(len(edges), dtype=float)
    num_negative = 0

    for j, e in enumerate(edges):
        u, v = e
        sign = assigned[e]
        if sign < 0:
            raw_phases[j] = np.pi
            num_negative += 1
        else:
            raw_phases[j] = 0.0
        H[u, v] = complex(sign)
        H[v, u] = complex(sign)

    return H, raw_phases, False, num_negative


def support_error(G: nx.Graph, H: Array) -> float:
    edge_set = {tuple(sorted((int(u), int(v)))) for u, v in G.edges()}
    n = H.shape[0]
    err = 0.0
    for u in range(n):
        for v in range(n):
            if u == v:
                err = max(err, abs(H[u, v]))
            elif tuple(sorted((u, v))) not in edge_set:
                err = max(err, abs(H[u, v]))
    return float(err)


def spectral_scale(H: Array) -> float:
    return float(max(1.0, np.linalg.norm(H, ord=2)))


def moment_vector(H: Array, source: int, target: int) -> Array:
    n = H.shape[0]
    moments = np.zeros(n, dtype=complex)
    power = np.eye(n, dtype=complex)
    for k in range(n):
        if k > 0:
            power = power @ H
        moments[k] = power[target, source]
    return moments


def objective_values(H: Array, source: int, target: int) -> Dict[str, float]:
    raw = moment_vector(H, source, target)
    alpha = spectral_scale(H)
    factors = np.array([alpha ** (-k) for k in range(H.shape[0])], dtype=float)
    normed = raw * factors
    return {
        "raw_objective": float(np.sum(np.abs(raw) ** 2)),
        "max_raw_moment": float(np.max(np.abs(raw))),
        "normalized_objective": float(np.sum(np.abs(normed) ** 2)),
        "max_normalized_moment": float(np.max(np.abs(normed))),
    }


def sector_errors(R: Array, source: int, target: int) -> Tuple[float, float, float]:
    n = R.shape[0]
    e_s = np.zeros(n)
    e_t = np.zeros(n)
    e_s[source] = 1.0
    e_t[target] = 1.0
    r2 = float(np.linalg.norm(R @ R - np.eye(n), ord="fro"))
    src = float(np.linalg.norm(R @ e_s - e_s))
    tgt = float(np.linalg.norm(R @ e_t + e_t))
    return r2, src, tgt


def commutator_norm(H: Array, R: Array) -> float:
    return float(np.linalg.norm(H @ R - R @ H, ord="fro"))


def cycle_fluxes(G: nx.Graph, raw_phases: Sequence[float]) -> List[float]:
    edges = canonical_edges(G)
    theta_by_edge = {edge: float(theta) for edge, theta in zip(edges, raw_phases)}
    fluxes: List[float] = []
    for cyc in nx.cycle_basis(G):
        if len(cyc) < 3:
            continue
        total = 0.0
        for a, b in zip(cyc, cyc[1:] + [cyc[0]]):
            a, b = int(a), int(b)
            edge = (min(a, b), max(a, b))
            theta = theta_by_edge[edge]
            total += theta if a < b else -theta
        fluxes.append(float(total % TWOPI))
    return fluxes


def format_fluxes(fluxes: Sequence[float], max_items: int = 20) -> str:
    if not fluxes:
        return "[]"
    shown = list(fluxes[:max_items])
    s = "[" + ", ".join(f"{x:.12g}" for x in shown)
    if len(fluxes) > max_items:
        s += f", ... +{len(fluxes)-max_items} more"
    s += "]"
    return s


def sign_assignments_for_pair(
    G: nx.Graph,
    r: Dict[int, int],
    source: int,
    target: int,
    max_enum_free_orbits: int,
    random_signs_per_pair: int,
    seed: int,
    sign_mode: str = "minimal",
) -> Iterable[Tuple[int, Dict[int, int], str]]:
    """
    Yield sign assignments sigma constant on r-orbits, with
        sigma_source = +1,
        sigma_target = -1.

    Returns tuples:
        sign_assignment_index, sigma_dict, mode_label
    """
    rng = np.random.default_rng(seed)
    orbits = vertex_orbits_under_involution(G, r)

    orbit_of: Dict[int, Tuple[int, ...]] = {}
    for orb in orbits:
        for v in orb:
            orbit_of[v] = orb

    if orbit_of[source] == orbit_of[target]:
        return

    fixed: Dict[Tuple[int, ...], int] = {
        orbit_of[source]: +1,
        orbit_of[target]: -1,
    }

    free_orbits = [orb for orb in orbits if orb not in fixed]

    def make_sigma(orb_signs: Dict[Tuple[int, ...], int]) -> Dict[int, int]:
        sigma = {}
        all_signs = dict(fixed)
        all_signs.update(orb_signs)
        for orb in orbits:
            val = int(all_signs.get(orb, +1))
            for v in orb:
                sigma[v] = val
        return sigma

    idx = 0

    # Minimal assignment: all free orbits +.
    yield idx, make_sigma({orb: +1 for orb in free_orbits}), "minimal"
    idx += 1

    if sign_mode == "minimal":
        return

    # Target-complement assignment: all free orbits -.
    if free_orbits:
        yield idx, make_sigma({orb: -1 for orb in free_orbits}), "all_free_negative"
        idx += 1

    if sign_mode == "two":
        return

    # Exhaustive small enumeration.
    if sign_mode == "enum" and len(free_orbits) <= max_enum_free_orbits:
        for bits in itertools.product([-1, +1], repeat=len(free_orbits)):
            signs = {orb: int(bit) for orb, bit in zip(free_orbits, bits)}
            # Skip duplicates of minimal/all_negative if already yielded.
            if all(v == +1 for v in signs.values()):
                continue
            if free_orbits and all(v == -1 for v in signs.values()):
                continue
            yield idx, make_sigma(signs), "enumerated"
            idx += 1
    elif sign_mode == "random":
        # Random assignments for larger orbit count.
        seen = set()
        for _ in range(random_signs_per_pair):
            bits = rng.choice([-1, +1], size=len(free_orbits))
            key = tuple(int(b) for b in bits)
            if key in seen:
                continue
            seen.add(key)
            signs = {orb: int(bit) for orb, bit in zip(free_orbits, bits)}
            yield idx, make_sigma(signs), "random"
            idx += 1


def classify_candidate(
    vals: Dict[str, float],
    comm: float,
    r2: float,
    src_err: float,
    tgt_err: float,
    supp_err: float,
    obstruction: bool,
    thresholds: Thresholds,
) -> Tuple[str, str]:
    if obstruction:
        return "rejected", "fixed_edge_obstruction"
    if supp_err >= thresholds.eps_support:
        return "rejected", "support_error"
    if r2 >= thresholds.eps_r2:
        return "rejected", "R_squared_not_identity"
    if src_err >= thresholds.eps_sector:
        return "rejected", "source_not_plus_sector"
    if tgt_err >= thresholds.eps_sector:
        return "rejected", "target_not_minus_sector"
    if comm >= thresholds.eps_comm:
        return "rejected", "commutator_nonzero"
    if vals["max_normalized_moment"] >= thresholds.eps_verify:
        return "failed", "moment_verification_failed"
    return "verified_numerical_candidate", "signed_involution_sector_proof_route"


def run_m3a(args) -> Tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    thresholds = Thresholds(
        eps_verify=args.eps_verify,
        eps_comm=args.eps_comm,
        eps_r2=args.eps_r2,
        eps_sector=args.eps_sector,
        eps_support=args.eps_support,
    )

    graphs = graph_suite(args.suite, seed=args.seed)

    if args.include_classes:
        include = {x.strip() for x in args.include_classes.split(",") if x.strip()}
        graphs = [g for g in graphs if g[1] in include]

    if args.exclude_classes:
        exclude = {x.strip() for x in args.exclude_classes.split(",") if x.strip()}
        graphs = [g for g in graphs if g[1] not in exclude]

    if args.max_graphs > 0:
        graphs = graphs[: args.max_graphs]

    graph_records: List[GraphRecord] = []
    candidate_records: List[CandidateRecord] = []
    phase_rows: List[Dict] = []
    flux_rows: List[Dict] = []
    rejected_rows: List[Dict] = []

    candidate_counter = 0
    seen_candidate_keys = set()

    for gi, (graph_id, graph_class, G, notes) in enumerate(graphs):
        G = nx.convert_node_labels_to_integers(G)
        if args.connected_only and not nx.is_connected(G):
            continue

        involutions = automorphism_involutions(G, max_automorphisms=args.max_automorphisms)
        graph_candidate_count = 0
        involutions_checked = 0

        if args.progress:
            print(
                f"[M3A] graph={graph_id} class={graph_class} "
                f"n={G.number_of_nodes()} m={G.number_of_edges()} "
                f"cycle_rank={cycle_rank(G)} involutions={len(involutions)}",
                flush=True,
            )

        for ai, r in enumerate(involutions):
            involutions_checked += 1
            fixed = fixed_vertices(r)

            if len(fixed) < 2:
                continue

            # Source and target must be fixed points of the underlying
            # involution so they can be pure + and - sector basis states.
            if args.undirected_pairs:
                ordered_pairs = [(s, t) for i, s in enumerate(fixed) for t in fixed[i+1:]]
            else:
                ordered_pairs = [(s, t) for s in fixed for t in fixed if s != t]

            if args.max_pairs_per_involution > 0:
                ordered_pairs = ordered_pairs[: args.max_pairs_per_involution]

            for source, target in ordered_pairs:
                for sign_idx, sigma, sign_mode in sign_assignments_for_pair(
                    G,
                    r,
                    source=source,
                    target=target,
                    max_enum_free_orbits=args.max_enum_free_orbits,
                    random_signs_per_pair=args.random_signs_per_pair,
                    seed=args.seed + 100000 * gi + 1000 * ai + 10 * source + target,
                    sign_mode=args.sign_mode,
                ):
                    if graph_candidate_count >= args.max_candidates_per_graph:
                        break

                    H, raw_phases, obstruction, num_negative = build_signed_magnetic_hamiltonian(G, r, sigma)

                    if obstruction or H is None or raw_phases is None:
                        if args.record_rejections:
                            rejected_rows.append({
                                "graph_id": graph_id,
                                "automorphism_index": ai,
                                "source": source,
                                "target": target,
                                "sign_assignment_index": sign_idx,
                                "reason": "fixed_edge_obstruction",
                                "sign_mode": sign_mode,
                            })
                        continue

                    R = signed_permutation_matrix(G, r, sigma)
                    vals = objective_values(H, source, target)
                    comm = commutator_norm(H, R)
                    r2, src_err, tgt_err = sector_errors(R, source, target)
                    supp_err = support_error(G, H)

                    status, reason = classify_candidate(
                        vals=vals,
                        comm=comm,
                        r2=r2,
                        src_err=src_err,
                        tgt_err=tgt_err,
                        supp_err=supp_err,
                        obstruction=False,
                        thresholds=thresholds,
                    )

                    if status != "verified_numerical_candidate" and not args.record_rejections:
                        continue

                    fluxes = cycle_fluxes(G, raw_phases)
                    flux_key = tuple(round(float(x), 10) for x in fluxes)
                    candidate_key = (graph_id, min(source, target), max(source, target), num_negative, flux_key)
                    if args.deduplicate and candidate_key in seen_candidate_keys:
                        continue
                    seen_candidate_keys.add(candidate_key)

                    candidate_counter += 1
                    graph_candidate_count += 1
                    candidate_id = f"M3A_{candidate_counter:06d}"

                    candidate_records.append(CandidateRecord(
                        candidate_id=candidate_id,
                        graph_id=graph_id,
                        graph_class=graph_class,
                        n=G.number_of_nodes(),
                        m=G.number_of_edges(),
                        cycle_rank=cycle_rank(G),
                        automorphism_index=ai,
                        sign_assignment_index=sign_idx,
                        source=source,
                        target=target,
                        status=status,
                        proof_route="signed_involution_sector",
                        normalized_objective=vals["normalized_objective"],
                        max_normalized_moment=vals["max_normalized_moment"],
                        raw_objective=vals["raw_objective"],
                        max_raw_moment=vals["max_raw_moment"],
                        commutator_norm=comm,
                        r2_error=r2,
                        source_plus_error=src_err,
                        target_minus_error=tgt_err,
                        support_error=supp_err,
                        fixed_edge_obstruction=False,
                        num_negative_edges=num_negative,
                        observed_fluxes=format_fluxes(fluxes),
                        involution_mapping_json=json.dumps({str(k): int(v) for k, v in sorted(r.items())}),
                        vertex_signs_json=json.dumps({str(k): int(v) for k, v in sorted(sigma.items())}),
                        notes=f"{notes} sign_mode={sign_mode}",
                    ))

                    edges = canonical_edges(G)
                    for edge_index, ((u, v), theta) in enumerate(zip(edges, raw_phases)):
                        phase_rows.append({
                            "candidate_id": candidate_id,
                            "graph_id": graph_id,
                            "edge_index": edge_index,
                            "u": u,
                            "v": v,
                            "theta": float(theta),
                            "theta_over_pi": float(theta / np.pi),
                            "edge_sign": int(+1 if abs(theta) < 1e-12 else -1),
                        })

                    for flux_index, flux in enumerate(fluxes):
                        # For 0/pi sign candidates, flux/pi is especially useful.
                        flux_rows.append({
                            "candidate_id": candidate_id,
                            "graph_id": graph_id,
                            "cycle_basis_index": flux_index,
                            "flux": float(flux),
                            "flux_over_pi": float(((flux + np.pi) % TWOPI - np.pi) / np.pi),
                        })

                    if args.stop_after_first:
                        break

                if graph_candidate_count >= args.max_candidates_per_graph or args.stop_after_first:
                    break

            if graph_candidate_count >= args.max_candidates_per_graph or args.stop_after_first:
                break

        graph_records.append(GraphRecord(
            graph_id=graph_id,
            graph_class=graph_class,
            n=G.number_of_nodes(),
            m=G.number_of_edges(),
            cycle_rank=cycle_rank(G),
            connected=nx.is_connected(G),
            num_involutions_checked=involutions_checked,
            num_candidates=graph_candidate_count,
            edges_json=json.dumps(canonical_edges(G)),
            notes=notes,
        ))

    graphs_df = pd.DataFrame([asdict(x) for x in graph_records])
    candidates_df = pd.DataFrame([asdict(x) for x in candidate_records])
    phases_df = pd.DataFrame(phase_rows)
    fluxes_df = pd.DataFrame(flux_rows)
    rejected_df = pd.DataFrame(rejected_rows)

    return graphs_df, candidates_df, phases_df, fluxes_df, rejected_df


def write_outputs(
    outdir: Path,
    graphs_df: pd.DataFrame,
    candidates_df: pd.DataFrame,
    phases_df: pd.DataFrame,
    fluxes_df: pd.DataFrame,
    rejected_df: pd.DataFrame,
) -> None:
    outdir.mkdir(parents=True, exist_ok=True)

    graphs_df.to_csv(outdir / "m3a_graph_records.csv", index=False)
    candidates_df.to_csv(outdir / "m3a_candidates.csv", index=False)
    phases_df.to_csv(outdir / "m3a_phase_records.csv", index=False)
    fluxes_df.to_csv(outdir / "m3a_flux_records.csv", index=False)
    rejected_df.to_csv(outdir / "m3a_rejections.csv", index=False)

    if not candidates_df.empty:
        summary = (
            candidates_df.groupby(["graph_class", "graph_id", "status", "proof_route"])
            .size()
            .reset_index(name="count")
            .sort_values(["graph_class", "graph_id", "status"])
        )
        summary.to_csv(outdir / "m3a_summary.csv", index=False)

        best = (
            candidates_df.sort_values(["max_normalized_moment", "normalized_objective"])
            .groupby("graph_id")
            .head(5)
        )
        best.to_csv(outdir / "m3a_best_candidates_per_graph.csv", index=False)
    else:
        pd.DataFrame().to_csv(outdir / "m3a_summary.csv", index=False)
        pd.DataFrame().to_csv(outdir / "m3a_best_candidates_per_graph.csv", index=False)

    with pd.option_context("display.max_columns", None, "display.width", 240):
        print("\n=== M3A Graph Summary ===")
        if not graphs_df.empty:
            print(graphs_df[[
                "graph_id", "graph_class", "n", "m", "cycle_rank",
                "num_involutions_checked", "num_candidates"
            ]].to_string(index=False))

        print("\n=== M3A Candidate Summary ===")
        if not candidates_df.empty:
            cols = [
                "candidate_id", "graph_id", "graph_class", "source", "target",
                "status", "normalized_objective", "max_normalized_moment",
                "commutator_norm", "num_negative_edges", "observed_fluxes"
            ]
            print(candidates_df[cols].head(40).to_string(index=False))
        else:
            print("No verified candidates found.")

        print("\nWrote outputs to:", outdir.resolve())
        for name in [
            "m3a_graph_records.csv",
            "m3a_candidates.csv",
            "m3a_phase_records.csv",
            "m3a_flux_records.csv",
            "m3a_rejections.csv",
            "m3a_summary.csv",
            "m3a_best_candidates_per_graph.csv",
        ]:
            print("-", outdir / name)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--outdir", default="m3a_outputs")
    parser.add_argument("--seed", type=int, default=20260526)

    parser.add_argument("--suite", choices=["small", "medium", "large"], default="small")
    parser.add_argument("--max-graphs", type=int, default=0)
    parser.add_argument("--connected-only", action="store_true", default=True)

    parser.add_argument("--max-automorphisms", type=int, default=300)
    parser.add_argument("--max-pairs-per-involution", type=int, default=6)
    parser.add_argument("--max-candidates-per-graph", type=int, default=12)
    parser.add_argument("--max-enum-free-orbits", type=int, default=0)
    parser.add_argument("--random-signs-per-pair", type=int, default=0)

    parser.add_argument("--eps-verify", type=float, default=1e-10)
    parser.add_argument("--eps-comm", type=float, default=1e-10)
    parser.add_argument("--eps-r2", type=float, default=1e-12)
    parser.add_argument("--eps-sector", type=float, default=1e-12)
    parser.add_argument("--eps-support", type=float, default=1e-12)

    parser.add_argument("--include-classes", default="", help="Comma-separated graph_class allowlist.")
    parser.add_argument("--exclude-classes", default="", help="Comma-separated graph_class blocklist.")
    parser.add_argument("--sign-mode", choices=["minimal", "two", "enum", "random"], default="minimal")
    parser.add_argument("--undirected-pairs", action="store_true", default=True)
    parser.add_argument("--directed-pairs", dest="undirected_pairs", action="store_false")
    parser.add_argument("--deduplicate", action="store_true", default=True)
    parser.add_argument("--no-deduplicate", dest="deduplicate", action="store_false")
    parser.add_argument("--record-rejections", action="store_true")
    parser.add_argument("--stop-after-first", action="store_true")
    parser.add_argument("--progress", action="store_true")

    args = parser.parse_args()

    graphs_df, candidates_df, phases_df, fluxes_df, rejected_df = run_m3a(args)
    write_outputs(
        Path(args.outdir),
        graphs_df=graphs_df,
        candidates_df=candidates_df,
        phases_df=phases_df,
        fluxes_df=fluxes_df,
        rejected_df=rejected_df,
    )


if __name__ == "__main__":
    main()
